### ISSUE TITLE
NeatEmpty may be too agressive

### ISSUE THREAD

**Issue by itaysk** [itaysk/kubectl-neat#18]
NeatEmpty will look for empty resources and clean up their entire hierarchy if necessary.  This was originally designed to handle the fact the Neaters may leave fields empty after they finish working, however it may not always work for the benefit of the user. 
consider the following common CRD in Istio:

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "foo"
spec:
  peers:
  - mtls: {}
```

`NeatEmpty` will end up deleting `.spec` altogether.

**Comment by curusarn** [comment]
Similar thing might happen with `emptyDir` volumes:
See this configuration example from official docs (https://kubernetes.io/docs/concepts/storage/volumes/#emptydir-configuration-example):
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```
