### ISSUE TITLE
Neat fails to remove `creationTimestamp: null` in deployment pod template (and maybe other templates)

### ISSUE THREAD

**Issue by spkane** [itaysk/kubectl-neat#64]
`kubectl create deployment test --image=test --namespace test --dry-run=client -o yaml --replicas=3 | kubectl neat`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: test
        name: test
```
