### ISSUE TITLE
kubectl neat removing resource values

### ISSUE THREAD

**Issue by dmitriishaburov** [itaysk/kubectl-neat#81]
Input:
```
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 1Gi
```

output after `| kubectl neat`:
```
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 50m
```

Maybe there's some default relation between requests and limits but would be nice to see them both usually
