### ISSUE TITLE
kubectl neat removes field from network policy

### ISSUE THREAD

**Issue by aoz-turk** [itaysk/kubectl-neat#85]
Hi,

https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic
https://kubernetes.io/docs/concepts/services-networking/network-policies/#allow-all-egress-traffic

If we use kubectl neat with two yaml files above, the end results are the same. However for network policies, removing the block below changes the behaviour.

```
  egress:
  - {}
```

An example:

`cat n.yaml`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
spec:
  podSelector:
    matchLabels:
      app: test
  egress:
  - {}
  policyTypes:
  - Egress
```

`kubectl neat -f n.yaml`
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
spec:
  podSelector:
    matchLabels:
      app: test
  policyTypes:
  - Egress
```

Expected output:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
spec:
  podSelector:
    matchLabels:
      app: test
  egress:
  - {}
  policyTypes:
  - Egress
```

Thanks!
